# Question 7: What is the average number of aces per match?

Using `statistics`

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

In [2]:
MINI_PROJECT_ROOT = Path.cwd().parents[2]

DATA_ROOT = (
    MINI_PROJECT_ROOT
    / "Tennis Schema"
    / "tennis_data"
)

PROCESSED_ROOT = DATA_ROOT / "processed"

TEAM_DATA_ROOT = DATA_ROOT / "Data"

In [3]:
statistics = pd.read_parquet(PROCESSED_ROOT / "statistics_clean.parquet")

statistics.loc[statistics["statistic_name"].str.contains("ace", case=False, na=False), "statistic_name"].value_counts()

statistic_name
aces    76257
Name: count, dtype: int64

In [ ]:
# Keep Match-Level Ace Totals

aces = statistics[(statistics["statistic_name"] == "aces")& (statistics["period"] == "ALL")]

aces[["match_id", "home_value", "away_value"]].head()

     match_id  home_value  away_value
0    11998445        12.0         6.0
71   11998446         6.0         3.0
125  11998447         8.0         4.0
178  11998448         4.0         0.0
232  11998449         6.0         4.0

In [7]:
# Keep the Latest Ace Snapshot per Match

aces_latest = (aces.sort_values("snapshot_date").drop_duplicates("match_id", keep="last"))

aces_latest[["match_id", "home_value", "away_value"]].head()

       match_id  home_value  away_value
10333  12021562         0.0         1.0
10387  12021566         0.0         2.0
10458  12021581        16.0        10.0
10529  12021589         1.0         0.0
10583  12021590         0.0         0.0

In [9]:
# Total aces per match

aces_latest["total_aces"] = (
    aces_latest["home_value"] + aces_latest["away_value"]
)

aces_latest[["match_id", "home_value", "away_value", "total_aces"]].head()

       match_id  home_value  away_value  total_aces
10333  12021562         0.0         1.0         1.0
10387  12021566         0.0         2.0         2.0
10458  12021581        16.0        10.0        26.0
10529  12021589         1.0         0.0         1.0
10583  12021590         0.0         0.0         0.0

In [12]:
# Get the average

average_aces_per_match = aces_latest["total_aces"].mean().round(2)

print(f"On average, a tennis match has {average_aces_per_match} aces")

On average, a tennis match has 5.39 aces